name: Deploy Weather Application

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - name: Build Pulumi project
        run: dotnet publish

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::595266861432:role/GithubWorkerRole
          aws-region: us-east-1

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5

      - name: Pulumi Login
        run: pulumi login s3://pulimi-state-595266861432-us-east-1-an/weather-infra/

      - name: Pulumi Stack Select
        run: pulumi stack select dev

      - name: Pulumi Preview
        run: pulumi preview

      - name: Pulumi Up
        run: pulumi up --yes
